# Generated by Django 6.0 on 2025-12-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='manual_pdf',
            field=models.FileField(blank=True, help_text='User manual PDF', null=True, upload_to='manuals/'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='manual_url',
            field=models.URLField(blank=True, help_text='URL to the manual if found online'),
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the maintenance task')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (Every 3 months)'), ('semi_annual', 'Semi-Annual (Every 6 months)'), ('annual', 'Annual (Yearly)'), ('as_needed', 'As Needed'), ('custom', 'Custom Interval')], default='monthly', max_length=20)),
                ('interval_days', models.IntegerField(blank=True, help_text="Custom interval in days (if frequency is 'custom')", null=True)),
                ('last_performed', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('professional', 'Requires Professional')], default='medium', max_length=20)),
                ('parts_needed', models.TextField(blank=True, help_text='List of parts or supplies needed')),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step instructions')),
                ('extracted_from_manual', models.BooleanField(default=False, help_text='Whether this was extracted from the manual')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='household.appliance')),
            ],
            options={
                'ordering': ['appliance', 'next_due', 'task_name'],
                'indexes': [models.Index(fields=['appliance', 'next_due'], name='household_m_applian_b186c2_idx')],
            },
        ),
    ]
