# Generated by Django 6.0 on 2025-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_appliance_manual_pdf_appliance_manual_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='label_image',
            field=models.ImageField(blank=True, help_text='Photo of appliance label/serial number plate', null=True, upload_to='appliance_labels/'),
        ),
    ]
