# Generated by Django 6.0 on 2025-12-13 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_appliance_label_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Full address of the house', max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, help_text='Users who can manage this house (edit access)', related_name='administered_houses', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(help_text='Users who own this house (full access)', related_name='owned_houses', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, help_text='Users who can view this house (read-only access)', related_name='viewed_houses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Houses',
                'ordering': ['address'],
            },
        ),
        migrations.AddField(
            model_name='appliance',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='household.house'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='household.house'),
        ),
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='household.house'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='household.house'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('house', 'invoice_number')},
        ),
    ]
