# Generated by Django 6.0 on 2025-12-13 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_add_house_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Subtotal (calculated from line items if available)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, help_text='General invoice description/notes'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Grand total (amount + tax_amount)', max_digits=10),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the line item', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Quantity', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line (quantity × unit_price)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appliances', models.ManyToManyField(blank=True, help_text='Appliances associated with this line item', related_name='invoice_line_items', to='household.appliance')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='household.invoice')),
                ('rooms', models.ManyToManyField(blank=True, help_text='Rooms associated with this line item', related_name='invoice_line_items', to='household.room')),
            ],
            options={
                'ordering': ['invoice', 'id'],
            },
        ),
    ]
