# Generated by Django 6.0 on 2025-12-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0005_add_invoice_line_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal (calculated from line items if available)', max_digits=10),
        ),
    ]
